jquery_lang_js.prototype.lang.en = {
	'Tot':'All',
	'Serveis':'Services',
    'Servei':'Service',
	"Dades":"Datasets",
    "Dataset":"Datasets",
	"Imatges":"Images",
	"Sensors":"Sensors",
    "Penetròmetre":"Penetrometer",
    "Sensor":"Sensor",
    "(Ex:Planejament o WMS)":"(eg planning or WMS)",
    "(Ex:Ortofoto)":"(Ex: Orthophoto)",
    "(Ex:Contaminació)":"(Ex:Pollution)",
    "Estat catàleg IDEC":"State IDEC catalog",
    "Total registres":"Total records",
    "Total Organismes proveïdors":"Total providers",
    "Total Dades":"Total data",
    "Organismes  proveïdors de Dades":"Total Data providers",
    "Total Serveis":"Total services",
    "Organismes  proveïdors de Serveis":"Total services providers",
    "Total Imatges":"Total Images",
    "Organismes  proveïdors Imatges":"Total images providers",
    
    "Total Visors":"Total viewers",
    "Organismes amb visors web":"web viewers providers",
    
    
    "Total Sensors":"Total Sensors",
    "Organismes  proveïdors de Sensors":"Total sensors providers",
    "Cerca per organisme":"Search by provider",
    "Cerca altres catàlegs":"Search other catalogues",
    "(Ex:Allaus o WMS)":"(Ex:Avalanches or WMS)",
    "(Ex:WMS o sondeig)":"(Ex:WMS o Geotechnical surveys)",
    "(Ex:Mapa geològic)":"(Ex:Geological map)",
    "(Ex:Sondeig)":"(Ex:Geotechnical surveys)",
    "Per a cercar informació, feu clic sobre el punt aproximat en què esteu interessats sobre el mapa":"For information, click the approximate point at which you are interested on the map",
    "Metadada":"Metadata",
    "Fitxa":"Data report",
    "Nova cerca":"New Search",
    "(Ex:Accelerògraf)":"(Ex:Accelerògraf)",
    "(Ex:Contaminació)":"(Ex:Pollution)",
     "Estat catàleg IDEC":"State IDEC Catalogue",
    "Cartografia geològica":"Geologic cartography",
    "Deformacions del terreny":"Ground deformations",
    "Geotèrmia":"Geothermics",
    "Informació nivològica i d'allaus":"Snowpack information and avalanches",
    "Riscos geològics":"Geological hazards",
    "Sismologia":"Seismology",
    "Sondejos":"Geotechnical surveys",
    "Sondeig":"Geotechnical survey",
    "Tècniques geofísiques":"Geohysical techniques",
    "Text lliure..":"Free text..",
    "Inici":"Home",
    "Versió 2.0":"Version 2.0",
    "Versió 4.0":"Version 4.0",
    "Cerca espacial:":"Spatial search:",
     "Font":"Source",
    "Filtrar resultats per":"Filter results by:",
    "Conjunts":"Sets",
    "Tipus":"Types",
    "Escales dades":"Datasets scales",
    "Anys informació":"Years",
    "Organitzacions":"Providers",
    "Sèries":"Series",
   "Títol":"Título",
    "Genera i prova enllaç":"Genera y prueba enlace",
    "Error de connexió amb CatalogConnector":"Error de connexión con CatalogConnector",
    "Zoom a":"Zoom a",
    "Cercant...":"Buscando...",
    "Creant ":"Creando ",
    "Exportar tots els resultats a CSV-EXCEL":"Export to CSV-EXCEL",
    "Exportar a KML":"Export to KML",
    "Manuals i vincles":"Tutorials and links",
    "Altres catàlegs:":"Other Catalogues:",
    "Només es pinten sobre el mapa el mateix número de resultats mostrats a la taula":"Only drawn on the map the same results shown in table",
    "Més detalls...":"More Details....",
    "Tots els resultats":"All records",
    "Visor de mapes IDEC":"IDEC Map viewer",
    "Accés a GeoLocal":"GeoLocal web site",
    "Visor GeoLocal":"GeoLocal Map viewer",
     "Nova cerca":"New search",
     "Visor":"Viewer",
     "Cerques parametritzades":"Parametric search",
     "El catàleg com a servei":"Catalog service",
     "Videos ajuda":"Videos help",
     "Catàleg de Georecursos":"Geoinformation catalog",
	"Added In":"text"
}