jquery_lang_js.prototype.lang.es = {
	'Tot':'Todo',
	'Serveis':'Servicios',
    'Servei':'Servicio',
	"Dades":"Datasets",
    "Dataset":"Datasets",
	"Imatges":"Imágenes",
	"Sensors":"Sensores",
    "Penetròmetre":"Penetrómetro",
    "Sensor":"Sensor",
    "(Ex:Planejament o WMS)":"(Ej:Planeamiento o WMS)",
    "(Ex:Ortofoto)":"(Ex:Ortofoto)",
    "(Ex:Contaminació)":"(Ex:Contaminación)",
    "Estat catàleg IDEC":"Estado catálogo IDEC",
    "Total registres":"Total registros",
    "Total Organismes  proveïdors":"Total organismes proveedores",
    "Total Dades":"Total datos",
    "Organismes  proveïdors de Dades":"Organismos proveedores de Datos",
    "Total Serveis":"Total servicios",
    "Organismes  proveïdors de Serveis":"Organismos proveedores de Servicios",
    "Total Visors":"Total visores",
    "Organismes amb visors web":"Organismos con visores web",
    
    "Total Imatges":"Total Imágenes",
    "Organismes  proveïdors Imatges":"Organismos proveedores de Imágenes",
    "Total Sensors":"Total Sensores",
    "Organismes  proveïdors de Sensors":"Organismos proveedores de Sensores",
    "Cerca per organisme":"Búsqueda por organismo",
    "Cerca altres catàlegs":"Búsqueda otros catálogos",   
    "(Ex:Allaus o WMS)":"(Ex:Aludes o WMS)",
    "(Ex:WMS o sondeig)":"(Ex:WMS o sondeo)",
    "(Ex:Mapa geològic)":"(Ex:Mapa geológico)",
    "(Ex:Sondeig)":"(Ex:Sondeo)",
    "Per a cercar informació, feu clic sobre el punt aproximat en què esteu interessats sobre el mapa":"Para buscar información, haga clic sobre el punto aproximado en que esté interesado sobre el mapa",
    "Metadada":"Metadato",
    "Fitxa":"Ficha",
    "Nova cerca":"Nueva búsqueda",
    "(Ex:Accelerògraf)":"(Ex:Accelerògraf)",
    "(Ex:Contaminació)":"(Ex:Contaminación)",
    "Estat catàleg IDEC":"Estado catálogo IDEC",
    "Cartografia geològica":"Cartografia geológica",
    "Deformacions del terreny":"Deformaciones del terreno",
    "Geotèrmia":"Geotérmia",
    "Informació nivològica i d'allaus":"Información nivológica y de aludes",
    "Riscos geològics":"Riesgos geològicos",
    "Sismologia":"Sismología",
    "Sondejos":"Sondeos",
    "Sondeig":"Sondeo",
    "Tècniques geofísiques":"Técnicas geofísicas",
    "Text lliure..":"Texto libre..",
    "Inici":"Inicio",
    "Versió 2.0":"Versió 2.0",
    "Versió 4.0":"Versión 4.0",
    "Cerca espacial:":"Búsqueda espacial:",
    "Font":"Fuente",   
    "Filtrar resultats per":"Filtrar resultados por:",
    "Conjunts":"Conjuntos",
    "Tipus":"Tipos",
    "Escales dades":"Escalas datos",
    "Anys informació":"Años información",
    "Organitzacions":"Organizaciones",
    "Sèries":"Séries",
    "Títol":"Título",
    "Genera i prova enllaç":"Genera y prueba enlace",
    "Error de connexió amb CatalogConnector":"Error de connexión con CatalogConnector",
    "Zoom a":"Zoom a",
    "Cercant...":"Buscando...",
    "Creant ":"Creando ",
    "Exportar tots els resultats a CSV-EXCEL":"Exportar todos los resultados a CSV_EXCEL",
    "Exportar a KML":"Exportar a KML",
    "Manuals i vincles":"Manuales y enlaces",
    "Altres catàlegs:":"Otros catálogos",
    "Només es pinten sobre el mapa el mateix número de resultats mostrats a la taula":"Solo se pintan en el mapa los mismos resultados mostrados en la tabla",
	"Més detalls...":"Más detalles...",
    "Tots els resultats":"Todos los resultados",
    "Visor de mapes IDEC":"Visor de mapas IDEC",
    "Accés a GeoLocal":"Acceso a GeoLocal",
    "Visor GeoLocal":"Visor GeoLocal",
     "Nova cerca":"Limpiar",
     "Visor":"Visor",
     "Cerques parametritzades":"Búsquedas parametrizadas",
     "El catàleg com a servei":"El catálogo como servicio",
     "Videos ajuda":"Videos ayuda",
     "Catàleg de Georecursos":"Catálogo de Georecursos",
    "Added In":"text"
}
  